# Generated by Django 2.2.5 on 2021-04-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210421_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='adress',
            new_name='address',
        ),
    ]
